int main(int argc, char** argv) {
	int test = 0;
	double d = 2.0;
	short s = 9;
	int ok;
	int test2 = 123;
	float test3;
	float test4 = 123.123f;
	char test5;
	char test6 = 'a';
	struct king;
	signed int test7;
	signed test8 = 0;
	long double gwaet;
	long long awd;
	signed cola;
	long long* test9;
	long double lk;
	long double* ab;
	test4 / test2;
	test++;
	int* ip;
	--test;
	long* lp;
	char* cp;
	double* dp;
	short* sp;
	float* fp;
	char *** pointerpointerpointer;
}